/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adventurewatersportsdesktop;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.BookingTicket;
import org.json.JSONObject;

/**
 *
 * @author darro
 */
public class DashboardWindow extends javax.swing.JFrame {

    /**
     * Creates new form HomeWindow
     */
    public DashboardWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jMenuIssueTicket = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuAddBoat = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuReport = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabIssueTicket = new javax.swing.JPanel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        jBtnIncrementPax = new javax.swing.JButton();
        jBtnDecrementPax = new javax.swing.JButton();
        jTextPaxCount = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JLabel();
        jPanelCommercialData = new javax.swing.JPanel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        jTextFieldRegistrationNumber = new javax.swing.JTextField();
        jTextFieldTransportProprieter = new javax.swing.JTextField();
        jTextFieldContactNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        jToggleBtnCommercialVehicle = new javax.swing.JToggleButton();
        javax.swing.JButton jBtnTicket = new javax.swing.JButton();
        javax.swing.JButton jBtnClearTicket = new javax.swing.JButton();
        jTabAddBoat = new javax.swing.JPanel();
        jTabReport = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("Adventure Water Sports");

        jMenuIssueTicket.setBackground(new java.awt.Color(153, 153, 153));
        jMenuIssueTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuIssueTicketMouseClicked(evt);
            }
        });

        // Default toggle button unseleted state
        // Set the toggle button to be initially not selected
        jToggleBtnCommercialVehicle.setSelected(false);

        // Disable the panel on toggle off
        jPanelCommercialData.setVisible(false);

        // Add the action listener to the toggle button
        jToggleBtnCommercialVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleBtnCommercialVehicleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ISSUE TICKET");

        javax.swing.GroupLayout jMenuIssueTicketLayout = new javax.swing.GroupLayout(jMenuIssueTicket);
        jMenuIssueTicket.setLayout(jMenuIssueTicketLayout);
        jMenuIssueTicketLayout.setHorizontalGroup(
            jMenuIssueTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuIssueTicketLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jMenuIssueTicketLayout.setVerticalGroup(
            jMenuIssueTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuIssueTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuAddBoat.setBackground(new java.awt.Color(153, 153, 153));
        jMenuAddBoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAddBoatMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD BOAT");

        javax.swing.GroupLayout jMenuAddBoatLayout = new javax.swing.GroupLayout(jMenuAddBoat);
        jMenuAddBoat.setLayout(jMenuAddBoatLayout);
        jMenuAddBoatLayout.setHorizontalGroup(
            jMenuAddBoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuAddBoatLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jMenuAddBoatLayout.setVerticalGroup(
            jMenuAddBoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuAddBoatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuReport.setBackground(new java.awt.Color(153, 153, 153));
        jMenuReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuReportMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REPORT");

        javax.swing.GroupLayout jMenuReportLayout = new javax.swing.GroupLayout(jMenuReport);
        jMenuReport.setLayout(jMenuReportLayout);
        jMenuReportLayout.setHorizontalGroup(
            jMenuReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuReportLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jMenuReportLayout.setVerticalGroup(
            jMenuReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMenuAddBoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jMenuReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addComponent(jMenuIssueTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jMenuIssueTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jMenuAddBoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jMenuReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabIssueTicket.setBackground(new java.awt.Color(255, 255, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Pax Count");

        jBtnIncrementPax.setText("+");
        jBtnIncrementPax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncrementPaxActionPerformed(evt);
            }
        });

        jBtnDecrementPax.setText("-");
        jBtnDecrementPax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDecrementPaxActionPerformed(evt);
            }
        });

        jTextPaxCount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextPaxCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextPaxCount.setText("0");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("per head price");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Amount");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("350");

        jTextFieldAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jTextFieldAmount.setText("Amount");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Registration no");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Transport Prop.");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Contact No.");

        jTextFieldRegistrationNumber.setText("GA-08-T-1214");
        jTextFieldRegistrationNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegistrationNumberActionPerformed(evt);
            }
        });

        jTextFieldTransportProprieter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTransportProprieterActionPerformed(evt);
            }
        });

        jTextFieldContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactNumberActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Commercial Vehicle");

        javax.swing.GroupLayout jPanelCommercialDataLayout = new javax.swing.GroupLayout(jPanelCommercialData);
        jPanelCommercialData.setLayout(jPanelCommercialDataLayout);
        jPanelCommercialDataLayout.setHorizontalGroup(
            jPanelCommercialDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCommercialDataLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelCommercialDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCommercialDataLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCommercialDataLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTransportProprieter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCommercialDataLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCommercialDataLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCommercialDataLayout.setVerticalGroup(
            jPanelCommercialDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCommercialDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanelCommercialDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCommercialDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldTransportProprieter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCommercialDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("DOLPHIN RIDE BOOKING");

        jToggleBtnCommercialVehicle.setText("Commercial Vehicle");
        jToggleBtnCommercialVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleBtnCommercialVehicleActionPerformed(evt);
            }
        });

        jBtnTicket.setText("Generate Ticket");
        jBtnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTicketActionPerformed(evt);
            }
        });

        jBtnClearTicket.setText("Clear");
        jBtnClearTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTabIssueTicketLayout = new javax.swing.GroupLayout(jTabIssueTicket);
        jTabIssueTicket.setLayout(jTabIssueTicketLayout);
        jTabIssueTicketLayout.setHorizontalGroup(
            jTabIssueTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTabIssueTicketLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jTabIssueTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTabIssueTicketLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jTabIssueTicketLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnDecrementPax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPaxCount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jBtnIncrementPax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(39, 39, 39))
                    .addGroup(jTabIssueTicketLayout.createSequentialGroup()
                        .addGroup(jTabIssueTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelCommercialData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleBtnCommercialVehicle))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTabIssueTicketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnClearTicket)
                .addGap(39, 39, 39))
            .addGroup(jTabIssueTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jTabIssueTicketLayout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(141, Short.MAX_VALUE)))
        );
        jTabIssueTicketLayout.setVerticalGroup(
            jTabIssueTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTabIssueTicketLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jTabIssueTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jBtnIncrementPax)
                    .addComponent(jBtnDecrementPax)
                    .addComponent(jTextPaxCount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jTabIssueTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleBtnCommercialVehicle)
                .addGap(18, 18, 18)
                .addComponent(jPanelCommercialData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jTabIssueTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnTicket)
                    .addComponent(jBtnClearTicket))
                .addGap(14, 14, 14))
            .addGroup(jTabIssueTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jTabIssueTicketLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(540, Short.MAX_VALUE)))
        );

        jTabAddBoat.setBackground(new java.awt.Color(255, 102, 204));

        javax.swing.GroupLayout jTabAddBoatLayout = new javax.swing.GroupLayout(jTabAddBoat);
        jTabAddBoat.setLayout(jTabAddBoatLayout);
        jTabAddBoatLayout.setHorizontalGroup(
            jTabAddBoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        jTabAddBoatLayout.setVerticalGroup(
            jTabAddBoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jTabReport.setBackground(new java.awt.Color(102, 255, 153));

        javax.swing.GroupLayout jTabReportLayout = new javax.swing.GroupLayout(jTabReport);
        jTabReport.setLayout(jTabReportLayout);
        jTabReportLayout.setHorizontalGroup(
            jTabReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jTabReportLayout.setVerticalGroup(
            jTabReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabIssueTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jTabAddBoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabIssueTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabAddBoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuIssueTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuIssueTicketMouseClicked
        // TODO add your handling code here:
        jTabIssueTicket.setVisible(true);
        jTabAddBoat.setVisible(false);
        jTabReport.setVisible(false);
    }//GEN-LAST:event_jMenuIssueTicketMouseClicked

    private void jMenuAddBoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAddBoatMouseClicked
        // TODO add your handling code here:
        jTabIssueTicket.setVisible(false);
        jTabAddBoat.setVisible(true);
        jTabReport.setVisible(false);
    }//GEN-LAST:event_jMenuAddBoatMouseClicked

    private void jMenuReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuReportMouseClicked
        // TODO add your handling code here:
        jTabIssueTicket.setVisible(false);
        jTabAddBoat.setVisible(false);
        jTabReport.setVisible(true);
    }//GEN-LAST:event_jMenuReportMouseClicked

    private void jTextFieldTransportProprieterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTransportProprieterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTransportProprieterActionPerformed

    private void jTextFieldContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactNumberActionPerformed

    // Generate ticket on Button clicked
    private void jBtnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTicketActionPerformed
        // TODO add your handling code here:
        
        // Get the TextField data for commercial bookings
        String registrationNumber = jTextFieldRegistrationNumber.getText();
        String proprieterName = jTextFieldTransportProprieter.getText();
        String contactNumber = jTextFieldContactNumber.getText();
        
        if (counter == 0 && estimatedAmount == 0) {
            JOptionPane.showMessageDialog(null, "Atleast 1 person is required to proceed with ticketing");
        } else if (counter != 0 && estimatedAmount != 0) {
            if (areVehicleDetailsEntered()) {     
                commercialApiCall(registrationNumber, proprieterName, contactNumber);
            } else {
                nonCommercialApiCall();
            }
        }
        
    }//GEN-LAST:event_jBtnTicketActionPerformed

    private void jBtnClearTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearTicketActionPerformed
        // TODO add your handling code here:
        
        // Clear the text Fields
        jTextPaxCount.setText("0");
        jTextFieldAmount.setText("0 Rs.");
        
        jTextFieldRegistrationNumber.setText("");
        jTextFieldTransportProprieter.setText("");
        jTextFieldContactNumber.setText("");
    }//GEN-LAST:event_jBtnClearTicketActionPerformed

    private void jToggleBtnCommercialVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleBtnCommercialVehicleActionPerformed
        // TODO add your handling code here:
        if(jToggleBtnCommercialVehicle.isSelected()) {
            jPanelCommercialData.setVisible(true);
        } else {
            jPanelCommercialData.setVisible(false);
        }
    }//GEN-LAST:event_jToggleBtnCommercialVehicleActionPerformed

    private void jBtnDecrementPaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDecrementPaxActionPerformed
        // TODO add your handling code here:
        if (counter > 0) {
            counter--;
        }
        
        jTextPaxCount.setText(String.valueOf(counter));
        
        if (counter != 0) {
            estimatedAmount = amountPerPaxRide(counter);
            jTextFieldAmount.setText(String.valueOf(estimatedAmount));
        } else {
            JOptionPane.showMessageDialog(null, "Requires pax above 1 to calculate estimated cost");
            jTextFieldAmount.setText("0");
        }
        
    }//GEN-LAST:event_jBtnDecrementPaxActionPerformed

    private void jBtnIncrementPaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncrementPaxActionPerformed
        // TODO add your handling code here:
        counter++;
        
        jTextPaxCount.setText(String.valueOf(counter));
        
        estimatedAmount = amountPerPaxRide(counter);
        jTextFieldAmount.setText(String.valueOf(estimatedAmount));
    }//GEN-LAST:event_jBtnIncrementPaxActionPerformed

    private void jTextFieldRegistrationNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegistrationNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegistrationNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardWindow().setVisible(true);
            }
        });
    }
    
    // Custome Variable declaration 
    int counter = 0;
    int perHeadPrice = 350;
    int estimatedAmount = 0;
    
    // Custom methods to calculate ticket amount for the given pax
    private int amountPerPaxRide(int pax) {
        return perHeadPrice * pax;
    }
    
    // Non Commercial vehicle api call
    private void nonCommercialApiCall() {
        
        String nonCommercialApiURL = Constants.URL + Constants.NON_COMMERCIAL_BOOKING_ENDPOINT;
        
        
            try {
                // Create the JSON object with pax and amount
                JSONObject jsonRequest = new JSONObject();
                jsonRequest.put("pax", counter);
                jsonRequest.put("amount", estimatedAmount);
            
                // Open the connection and set up the request
                URL url = new URL(nonCommercialApiURL);
                HttpURLConnection connect = (HttpURLConnection) url.openConnection();
                connect.setRequestMethod("POST");
                connect.setRequestProperty("Content-Type", "application/json");
                connect.setDoOutput(true);
            
                // Write the JSON payload to request body
                try (OutputStream os = connect.getOutputStream()) {
                    byte[] input = jsonRequest.toString().getBytes("utf-8");
                    os.write(input, 0, input.length);
                } catch (IOException ex) {
                    Logger.getLogger(DashboardWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            
                // Get the response from the server
                BufferedReader br = new BufferedReader(new InputStreamReader(connect.getInputStream()));
                StringBuilder response = new StringBuilder();
                String line;
                while((line = br.readLine()) != null) {
                    response.append(line);
                }
                
                // Parse the JSON response
                JSONObject jsonResponse = new JSONObject(response.toString());
                
                // Check if the status is 200 (success)
                if (jsonResponse.getInt("status") == 200) {
                    JSONObject result = jsonResponse.getJSONObject("result");
                    JSONObject order = result.getJSONObject("order");
                    
                    BookingTicket bookingData = new BookingTicket(
                            order.getInt("serial_number"),
                            order.getInt("amount"),
                            order.getInt("pax")
                    );
                    
                    // Show the serial number, amount and pax in dialog
                    String message = "Serial Number: " + bookingData.getSerialNumber() +
                            "\nAmount: " + bookingData.getAmount() +
                            "\nPax: " + bookingData.getPax();
                    
                    JOptionPane.showMessageDialog(null, message);
                }
                
                br.close();
            
                // Print in the terminal the response
                System.out.println("Response " + response.toString());
            
                connect.disconnect();
            
            } catch (MalformedURLException ex) {
                Logger.getLogger(DashboardWindow.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ProtocolException ex) {
                Logger.getLogger(DashboardWindow.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(DashboardWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    
    // Commercial API call
    private void commercialApiCall(String registrationNumber, String transportProp, String contactNumber) {
        String nonCommercialApiURL = Constants.URL + Constants.COMMERCIAL_BOOKING_ENDPOINT;
        
        
        try {
            // Create the JSON object with pax and amount
            JSONObject jsonRequest = new JSONObject();
            jsonRequest.put("pax", counter);
            jsonRequest.put("amount", estimatedAmount);
            jsonRequest.put("reg_no", registrationNumber);
            jsonRequest.put("name", transportProp);
            jsonRequest.put("contact", contactNumber);
            
            // Open the connection and set up the request
            URL url = new URL(nonCommercialApiURL);
            HttpURLConnection connect = (HttpURLConnection) url.openConnection();
            connect.setRequestMethod("POST");
            connect.setRequestProperty("Content-Type", "application/json");
            connect.setDoOutput(true);
            
            // Write the JSON payload to request body
            try (OutputStream os = connect.getOutputStream()) {
                byte[] input = jsonRequest.toString().getBytes("utf-8");
                os.write(input, 0, input.length);
            } catch (IOException ex) {
                Logger.getLogger(DashboardWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            // Get the response from the server
            BufferedReader br = new BufferedReader(new InputStreamReader(connect.getInputStream()));
            StringBuilder response = new StringBuilder();
            String line;
            while((line = br.readLine()) != null) {
                response.append(line);
            }
            br.close();
            
            // Parse the JSON response
            JSONObject jsonResponse = new JSONObject(response.toString());
                
            // Check if the status is 200 (success)
            if (jsonResponse.getInt("status") == 200) {
                JSONObject result = jsonResponse.getJSONObject("result");
                JSONObject order = result.getJSONObject("order");
                    
                BookingTicket bookingData = new BookingTicket(
                        order.getInt("serial_number"),
                        order.getInt("amount"),
                        order.getInt("pax")
                );
                    
                // Show the serial number, amount and pax in dialog
                String message = "Serial Number: " + bookingData.getSerialNumber() +
                        "\nAmount: " + bookingData.getAmount() +
                        "\nPax: " + bookingData.getPax();
                    
                JOptionPane.showMessageDialog(null, message);
            }
            
            // Print in the terminal the response
            System.out.println("Response " + response.toString());
            
            connect.disconnect();
            
        } catch (MalformedURLException ex) {
            Logger.getLogger(DashboardWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ProtocolException ex) {
            Logger.getLogger(DashboardWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DashboardWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Check if Commercial vehicle details entered
    private boolean areVehicleDetailsEntered() {
        String registrationNumber = jTextFieldRegistrationNumber.getText();
        String proprieterName = jTextFieldTransportProprieter.getText();
        String contactNumber = jTextFieldContactNumber.getText();
        
        return !registrationNumber.isEmpty() && !proprieterName.isEmpty() && !contactNumber.isEmpty();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDecrementPax;
    private javax.swing.JButton jBtnIncrementPax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jMenuAddBoat;
    private javax.swing.JPanel jMenuIssueTicket;
    private javax.swing.JPanel jMenuReport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCommercialData;
    private javax.swing.JPanel jTabAddBoat;
    private javax.swing.JPanel jTabIssueTicket;
    private javax.swing.JPanel jTabReport;
    private javax.swing.JLabel jTextFieldAmount;
    private javax.swing.JTextField jTextFieldContactNumber;
    private javax.swing.JTextField jTextFieldRegistrationNumber;
    private javax.swing.JTextField jTextFieldTransportProprieter;
    private javax.swing.JLabel jTextPaxCount;
    private javax.swing.JToggleButton jToggleBtnCommercialVehicle;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
